<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Flood Incidents Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        h1 { font-size: 18px; margin-bottom: 2px; }
        .subtitle { color: #6b7280; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #1e40af; color: #fff; text-align: left; padding: 6px; font-size: 10px; }
        td { padding: 6px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) td { background: #f9fafb; }
        .severity-critical { color: #dc2626; font-weight: bold; }
        .severity-warning { color: #d97706; font-weight: bold; }
        .footer { margin-top: 16px; font-size: 9px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <h1>BahaAI — Flood Incidents Report</h1>
    <div class="subtitle">
        Municipality of Consolacion, Cebu
        @if($from || $to)
            &middot; Period: {{ $from ?? 'start' }} to {{ $to ?? 'present' }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Zone</th>
                <th>Barangay</th>
                <th>Severity</th>
                <th>Peak (m)</th>
                <th>Rain (mm)</th>
                <th>Duration</th>
                <th>Affected</th>
            </tr>
        </thead>
        <tbody>
            @forelse($incidents as $incident)
                <tr>
                    <td>{{ $incident->occurred_at->format('Y-m-d H:i') }}</td>
                    <td>{{ $incident->floodZone->name }}</td>
                    <td>{{ $incident->floodZone->barangay }}</td>
                    <td class="severity-{{ $incident->severity }}">{{ ucfirst($incident->severity) }}</td>
                    <td>{{ $incident->peak_water_level }}</td>
                    <td>{{ $incident->total_rainfall }}</td>
                    <td>{{ $incident->duration_minutes }} min</td>
                    <td>{{ $incident->affected_residents }}</td>
                </tr>
            @empty
                <tr><td colspan="8" style="text-align:center; padding: 20px;">No incidents in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by BahaAI on {{ $generatedAt->format('Y-m-d H:i') }} &middot; {{ $incidents->count() }} incident(s)
    </div>
</body>
</html>
